#
# Builds the C++ standard document on Travis CI <https://travis-ci.org/cpluscplus/draft>
#

env:
  - BUILD_TYPE=latexmk   # build using latexmk
  - BUILD_TYPE=make      # build using Makefile
  - BUILD_TYPE=manual    # build manually
  - BUILD_TYPE=complete  # build manually and regenerate figures, grammer, and cross-references
  - BUILD_TYPE=tests     # run tests only

script:
  # Build std.pdf
  - if [ "$BUILD_TYPE" = "latexmk" ]; then
      pushd source;
      latexmk -pdf std;
      popd;
    fi
  - if [ "$BUILD_TYPE" = "make" ]; then
      pushd source;
      make -j2;
      popd;
    fi
  - if [ "$BUILD_TYPE" = "complete" ]; then
      pushd source;
      for FIGURE in *.dot; do
        dot -o$(basename $FIGURE .dot).pdf -Tpdf $FIGURE;
      done;
      ../tools/makegram;
      ../tools/makexref;
      popd;
    fi
  - if [ "$BUILD_TYPE" = "manual" -o "$BUILD_TYPE" = "complete" ]; then
      pushd source;
      pdflatex std;
      pdflatex std;
      pdflatex std;
      makeindex generalindex;
      makeindex libraryindex;
      makeindex grammarindex;
      makeindex impldefindex;
      pdflatex std;
      pdflatex std;
      popd;
    fi
  - if [ "$BUILD_TYPE" = "tests" ]; then
      export TESTS_STATUS=0;
      pushd source;
      ../tools/makegram &&
      GRAMMAR_CHANGED=$(git status --porcelain grammar.tex);
      if [ ! -z "$GRAMMAR_CHANGED" ]; then
        git diff grammar.tex;
        export TESTS_STATUS=1;
      fi;
      ../tools/makexref &&
      XREF_CHANGED=$(git status --porcelain xref.tex);
      if [ ! -z "$XREF_CHANGED" ]; then
        git diff xref.tex;
        export TESTS_STATUS=1;
      fi;
      popd;
      if [ "$TESTS_STATUS" -ne "0" ]; then
        false;
      fi;
    fi

sudo: false

addons:
  apt:
    packages:
    - latexmk
    - poppler-utils
    - texlive-binaries
    - texlive-fonts-recommended
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-binaries
    - graphviz
    - lmodern
